# Assignment 1: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np #common convention

In [2]:
#3.2: create a random 10x10 array named A
A=np.random.rand(10,10)
A

array([[0.79541628, 0.6115991 , 0.0508841 , 0.80153621, 0.97859682,
        0.71804229, 0.30348694, 0.07567331, 0.54357221, 0.35691617],
       [0.22407788, 0.96331901, 0.73023474, 0.79169172, 0.25246688,
        0.39151654, 0.2723538 , 0.87256881, 0.43375959, 0.70893001],
       [0.34129957, 0.21421909, 0.00326712, 0.99539228, 0.30414682,
        0.06253958, 0.83043845, 0.68973151, 0.71277637, 0.95527947],
       [0.13902187, 0.96764227, 0.47311603, 0.06799207, 0.34724495,
        0.63024505, 0.52495666, 0.27849716, 0.16427169, 0.39332025],
       [0.7956952 , 0.61829349, 0.8894295 , 0.74132223, 0.95842764,
        0.56014711, 0.87413695, 0.09858975, 0.74636009, 0.29717319],
       [0.22750624, 0.52421764, 0.55994825, 0.21220304, 0.93391568,
        0.15504021, 0.02688323, 0.14454654, 0.84684987, 0.51361106],
       [0.23946059, 0.25691621, 0.66654306, 0.95232963, 0.06700181,
        0.3256592 , 0.17811161, 0.40867576, 0.04524465, 0.11500294],
       [0.56109186, 0.65963073, 0.7397798

In [3]:
#3.3: return only the odd rows of A
A[1::2]

array([[0.22407788, 0.96331901, 0.73023474, 0.79169172, 0.25246688,
        0.39151654, 0.2723538 , 0.87256881, 0.43375959, 0.70893001],
       [0.13902187, 0.96764227, 0.47311603, 0.06799207, 0.34724495,
        0.63024505, 0.52495666, 0.27849716, 0.16427169, 0.39332025],
       [0.22750624, 0.52421764, 0.55994825, 0.21220304, 0.93391568,
        0.15504021, 0.02688323, 0.14454654, 0.84684987, 0.51361106],
       [0.56109186, 0.65963073, 0.73977988, 0.39179065, 0.64833488,
        0.8755109 , 0.43834629, 0.15878653, 0.14132642, 0.7150376 ],
       [0.51016362, 0.76421294, 0.19511465, 0.07975668, 0.9976255 ,
        0.61193907, 0.98423417, 0.15958171, 0.85882971, 0.41656865]])

In [4]:
#3.4: perform a matrix multiplication of A with it's transposed
np.dot(A,A.T)

array([[3.64571713, 2.6048101 , 2.57566541, 1.98338516, 3.77515091,
        2.38814359, 1.59486908, 2.94159876, 2.73190184, 3.2890061 ],
       [2.6048101 , 3.88151978, 2.98895202, 2.43310649, 3.33009736,
        2.29423668, 2.19251261, 2.94416432, 3.41855995, 2.62272067],
       [2.57566541, 2.98895202, 3.83557478, 1.58984097, 3.08115575,
        1.91302337, 1.69952491, 2.23448587, 2.75595659, 2.69705673],
       [1.98338516, 2.43310649, 1.58984097, 2.23673441, 2.59178349,
        1.63573835, 1.15048878, 2.44863752, 2.24498936, 2.50628494],
       [3.77515091, 3.33009736, 3.08115575, 2.59178349, 5.00761013,
        2.96486404, 2.15877667, 3.63132544, 3.94346237, 4.05091432],
       [2.38814359, 2.29423668, 1.91302337, 1.63573835, 2.96486404,
        2.5839388 , 1.03878305, 2.23371877, 2.52177029, 2.66021175],
       [1.59486908, 2.19251261, 1.69952491, 1.15048878, 2.15877667,
        1.03878305, 1.79911423, 1.73018846, 2.17245176, 1.11792082],
       [2.94159876, 2.94416432, 2.2344858

In [5]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)

array([[ 4.01443612e-01,  3.01524465e+00, -8.72111828e-01,
        -2.68889873e+00,  2.04538408e+00, -1.99356779e+00,
        -3.11302926e+00,  7.15034967e-01, -5.05894483e-02,
        -2.74811619e-01],
       [ 8.74686203e-01,  2.21874948e-01,  2.06203775e-01,
         2.25116713e+00,  1.19361139e+00, -8.99603805e-02,
        -1.61193197e+00, -1.21923673e+00,  7.84768343e-02,
        -1.97613955e+00],
       [-8.09485906e-01,  1.36737150e-01, -2.61598377e-01,
        -2.28895507e-01,  6.72553340e-01,  3.01718871e-01,
         2.19041911e-01,  3.58610832e-01, -8.97220073e-02,
        -1.96112347e-01],
       [ 6.86601594e-01, -1.49480222e+00,  8.56961520e-01,
         1.96505599e+00,  1.26680120e-01,  6.93226401e-01,
         9.87450260e-01, -9.46340157e-01, -5.71287361e-02,
        -1.42336118e+00],
       [ 3.36083230e-02, -3.75086298e-01, -8.26232728e-01,
        -3.06010726e+00, -3.33539114e+00, -3.01882672e-01,
         1.00154747e+00,  2.07934895e+00,  2.06023356e+00,
         3.

In [6]:
A

array([[0.79541628, 0.6115991 , 0.0508841 , 0.80153621, 0.97859682,
        0.71804229, 0.30348694, 0.07567331, 0.54357221, 0.35691617],
       [0.22407788, 0.96331901, 0.73023474, 0.79169172, 0.25246688,
        0.39151654, 0.2723538 , 0.87256881, 0.43375959, 0.70893001],
       [0.34129957, 0.21421909, 0.00326712, 0.99539228, 0.30414682,
        0.06253958, 0.83043845, 0.68973151, 0.71277637, 0.95527947],
       [0.13902187, 0.96764227, 0.47311603, 0.06799207, 0.34724495,
        0.63024505, 0.52495666, 0.27849716, 0.16427169, 0.39332025],
       [0.7956952 , 0.61829349, 0.8894295 , 0.74132223, 0.95842764,
        0.56014711, 0.87413695, 0.09858975, 0.74636009, 0.29717319],
       [0.22750624, 0.52421764, 0.55994825, 0.21220304, 0.93391568,
        0.15504021, 0.02688323, 0.14454654, 0.84684987, 0.51361106],
       [0.23946059, 0.25691621, 0.66654306, 0.95232963, 0.06700181,
        0.3256592 , 0.17811161, 0.40867576, 0.04524465, 0.11500294],
       [0.56109186, 0.65963073, 0.7397798

In [7]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
mask = A > 0.5
indice=np.where(mask)
A[indice]=A[indice]/2
A

array([[0.39770814, 0.30579955, 0.0508841 , 0.4007681 , 0.48929841,
        0.35902114, 0.30348694, 0.07567331, 0.2717861 , 0.35691617],
       [0.22407788, 0.48165951, 0.36511737, 0.39584586, 0.25246688,
        0.39151654, 0.2723538 , 0.43628441, 0.43375959, 0.354465  ],
       [0.34129957, 0.21421909, 0.00326712, 0.49769614, 0.30414682,
        0.06253958, 0.41521923, 0.34486576, 0.35638819, 0.47763974],
       [0.13902187, 0.48382114, 0.47311603, 0.06799207, 0.34724495,
        0.31512253, 0.26247833, 0.27849716, 0.16427169, 0.39332025],
       [0.3978476 , 0.30914674, 0.44471475, 0.37066111, 0.47921382,
        0.28007356, 0.43706848, 0.09858975, 0.37318004, 0.29717319],
       [0.22750624, 0.26210882, 0.27997413, 0.21220304, 0.46695784,
        0.15504021, 0.02688323, 0.14454654, 0.42342494, 0.25680553],
       [0.23946059, 0.25691621, 0.33327153, 0.47616482, 0.06700181,
        0.3256592 , 0.17811161, 0.40867576, 0.04524465, 0.11500294],
       [0.28054593, 0.32981537, 0.3698899